name: PR Lint Check

on:
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4

      - name: Setup Node version and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - run: npm ci
      
      # Lint only affected projects
      # - name: Lint affected projects
      #   run: npx nx affected --target=lint
      
      # Lint all projects 
      - name: Lint all projects
        run: npx nx run-many --target=lint --all 